### ISSUE TITLE
闪退

### ISSUE THREAD

**Issue by pangyu646182805** [sunhapper/SpEditTool#17]
demo点击表情之后选择#topic#然后删除会闪退

**Comment by sunhapper** [comment]
我试了下没出现崩溃，麻烦发下出错堆栈，谢谢

**Comment by pangyu646182805** [comment]
闪退的是vivo x6d 系统5.1 其他手机试了确实没闪退
java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter what
        at com.sunhapper.x.spedit.mention.watcher.SpanChangedWatcher.onSpanChanged(SpanChangedWatcher.kt)
        at android.text.SpannableStringBuilder.sendSpanChanged(SpannableStringBuilder.java:1019)
        at android.text.SpannableStringBuilder.sendToSpanWatchers(SpannableStringBuilder.java:601)
        at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:532)
        at com.sunhapper.x.spedit.view.EmojiSpannableStringBuilder.replace(EmojiSpannableStringBuilder.kt:256)
        at android.text.SpannableStringBuilder.delete(SpannableStringBuilder.java:224)
        at com.sunhapper.x.spedit.view.EmojiSpannableStringBuilder.delete(EmojiSpannableStringBuilder.kt:273)
        at com.sunhapper.x.spedit.view.EmojiSpannableStringBuilder.delete(EmojiSpannableStringBuilder.kt:12)
