### ISSUE TITLE
IllegalArgumentException: PrecomputedText's Parameters don't match the parameters of this TextView.Consider using setTextMetricsParams(precomputedText.getParams()) to override the settings of this TextView: PrecomputedText:

### ISSUE THREAD

**Issue by wlpsunny** [sunhapper/SpEditTool#28]
Caused by: java.lang.IllegalArgumentException: PrecomputedText's Parameters don't match the parameters of this TextView.Consider using setTextMetricsParams(precomputedText.getParams()) to override the settings of this TextView: PrecomputedText: {textSize=45.0, textScaleX=1.0, textSkewX=0.0, letterSpacing=0.0, textLocale=[zh_CN], typeface=android.graphics.Typeface@5cb73da, variationSettings=null, elegantTextHeight=false, textDir=android.text.TextDirectionHeuristics$TextDirectionHeuristicInternal@a4e222a, breakStrategy=0, hyphenationFrequency=0, lineBreakStyle=0, lineBreakWordStyle=0}TextView: {textSize=45.0, textScaleX=1.0, textSkewX=0.0, letterSpacing=0.0, textLocale=[zh_CN], typeface=android.graphics.Typeface@5cb73da, variationSettings=null, elegantTextHeight=false, textDir=android.text.TextDirectionHeuristics$TextDirectionHeuristicInternal@a4e222a, breakStrategy=0, hyphenationFrequency=0, lineBreakStyle=0, lineBreakWordStyle=0}
2.at android.widget.TextView.setText(TextView.java:6554)
3.at android.widget.TextView.setText(TextView.java:6472)
4.at com.sunhapper.x.spedit.view.SpXTextView.setText(SpXTextView.java:36)
5.at android.widget.TextView.setText(TextView.java:6424)

**Comment by wlpsunny** [comment]
机型是 魅族20  和魅族20pro  Android13
